default:
    title: emoticode - Snippets and Source Code Search Engine
    description: EmotiCODE is a code snippet search engine but mostly a place where developers can find help for what they need and contribute with their own contents.
    keywords: emoticode, snippets, code snippets, source, source code, programming, programmer, %s
    metas: 
        - :charset: utf-8
        - :property: og:locale
          :content: en_US
        - :property: og:site_name
          :content: emoticode
        - :property: og:image
          :content: http://www.emoticode.net/assets/style/logo-200.png?v=2.1
        - :property: fb_app_id
          :content: '541383999216397'
        - :property: fb:app_id
          :content: '541383999216397'
        - :property: og:url
          :content: http://www.emoticode.net/
        - :name: language
          :content: en
        - :name: robots
          :content: noodp,noydr
        - :name: alexaVerifyID
          :content: esKfarSO5NWalbJaefzTwaUzso
        - :name: msvalidate.01
          :content: 9C2A48C8F5733D97CD13C5EB3699308D
        - :name: google-site-verification
          :content: Uy9LP869XtH59q7mfCgyOd4CS5XifoRgROn0wJ8d8MU

language:
    description: All %s Snippets from EmotiCODE, a %s code snippet search engine but mostly a place where developers can find help for what they need and contribute with their own contents.
    keywords: Every %s snippets, %s code, %s codes, %s code snippets, %s snippet archive

user:
    description: EmotiCODE %s Profile

search:
    description: Searching for %s inside EmotiCODE, a source code snippet search engine but mostly a place where developers can find help for what they need and contribute with their own contents.
